/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "dragcfact.c"
#include "restartsig.c"
#include "renamed_scratchpads.c"
#include "shift.c"
#include "shiftboth.c"
#include "shifttag.c"
#include "shiftview.c"
#include "stacker.c"
#include "sticky.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "xrdb.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_monocle.c"
#include "layout_tile.c"

